package io.github.plixo2.sodalite.category.pixels;

import io.github.plixo2.sodalite.Internal;
import io.github.plixo2.sodalite.category.gpu.GPU;
import io.github.plixo2.sodalite.category.gpu.TextureFormat;
import lombok.RequiredArgsConstructor;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.Nullable;

import static org.libsdl.sdl.SDL3_h.*;

/// @sdlAPI SDL_PixelFormat
@RequiredArgsConstructor
public enum PixelFormat {
    UNKNOWN(SDL_PIXELFORMAT_UNKNOWN()),
    INDEX1LSB(SDL_PIXELFORMAT_INDEX1LSB()),
    INDEX1MSB(SDL_PIXELFORMAT_INDEX1MSB()),
    INDEX2LSB(SDL_PIXELFORMAT_INDEX2LSB()),
    INDEX2MSB(SDL_PIXELFORMAT_INDEX2MSB()),
    INDEX4LSB(SDL_PIXELFORMAT_INDEX4LSB()),
    INDEX4MSB(SDL_PIXELFORMAT_INDEX4MSB()),
    INDEX8(SDL_PIXELFORMAT_INDEX8()),
    RGB332(SDL_PIXELFORMAT_RGB332()),
    XRGB4444(SDL_PIXELFORMAT_XRGB4444()),
    XBGR4444(SDL_PIXELFORMAT_XBGR4444()),
    XRGB1555(SDL_PIXELFORMAT_XRGB1555()),
    XBGR1555(SDL_PIXELFORMAT_XBGR1555()),
    ARGB4444(SDL_PIXELFORMAT_ARGB4444()),
    RGBA4444(SDL_PIXELFORMAT_RGBA4444()),
    ABGR4444(SDL_PIXELFORMAT_ABGR4444()),
    BGRA4444(SDL_PIXELFORMAT_BGRA4444()),
    ARGB1555(SDL_PIXELFORMAT_ARGB1555()),
    RGBA5551(SDL_PIXELFORMAT_RGBA5551()),
    ABGR1555(SDL_PIXELFORMAT_ABGR1555()),
    BGRA5551(SDL_PIXELFORMAT_BGRA5551()),
    RGB565(SDL_PIXELFORMAT_RGB565()),
    BGR565(SDL_PIXELFORMAT_BGR565()),
    RGB24(SDL_PIXELFORMAT_RGB24()),
    BGR24(SDL_PIXELFORMAT_BGR24()),
    XRGB8888(SDL_PIXELFORMAT_XRGB8888()),
    RGBX8888(SDL_PIXELFORMAT_RGBX8888()),
    XBGR8888(SDL_PIXELFORMAT_XBGR8888()),
    BGRX8888(SDL_PIXELFORMAT_BGRX8888()),
    ARGB8888(SDL_PIXELFORMAT_ARGB8888()),
    RGBA8888(SDL_PIXELFORMAT_RGBA8888()),
    ABGR8888(SDL_PIXELFORMAT_ABGR8888()),
    BGRA8888(SDL_PIXELFORMAT_BGRA8888()),
    XRGB2101010(SDL_PIXELFORMAT_XRGB2101010()),
    XBGR2101010(SDL_PIXELFORMAT_XBGR2101010()),
    ARGB2101010(SDL_PIXELFORMAT_ARGB2101010()),
    ABGR2101010(SDL_PIXELFORMAT_ABGR2101010()),
    RGB48(SDL_PIXELFORMAT_RGB48()),
    BGR48(SDL_PIXELFORMAT_BGR48()),
    RGBA64(SDL_PIXELFORMAT_RGBA64()),
    ARGB64(SDL_PIXELFORMAT_ARGB64()),
    BGRA64(SDL_PIXELFORMAT_BGRA64()),
    ABGR64(SDL_PIXELFORMAT_ABGR64()),
    RGB48_FLOAT(SDL_PIXELFORMAT_RGB48_FLOAT()),
    BGR48_FLOAT(SDL_PIXELFORMAT_BGR48_FLOAT()),
    RGBA64_FLOAT(SDL_PIXELFORMAT_RGBA64_FLOAT()),
    ARGB64_FLOAT(SDL_PIXELFORMAT_ARGB64_FLOAT()),
    BGRA64_FLOAT(SDL_PIXELFORMAT_BGRA64_FLOAT()),
    ABGR64_FLOAT(SDL_PIXELFORMAT_ABGR64_FLOAT()),
    RGB96_FLOAT(SDL_PIXELFORMAT_RGB96_FLOAT()),
    BGR96_FLOAT(SDL_PIXELFORMAT_BGR96_FLOAT()),
    RGBA128_FLOAT(SDL_PIXELFORMAT_RGBA128_FLOAT()),
    ARGB128_FLOAT(SDL_PIXELFORMAT_ARGB128_FLOAT()),
    BGRA128_FLOAT(SDL_PIXELFORMAT_BGRA128_FLOAT()),
    ABGR128_FLOAT(SDL_PIXELFORMAT_ABGR128_FLOAT()),
    YV12(SDL_PIXELFORMAT_YV12()),
    IYUV(SDL_PIXELFORMAT_IYUV()),
    YUY2(SDL_PIXELFORMAT_YUY2()),
    UYVY(SDL_PIXELFORMAT_UYVY()),
    YVYU(SDL_PIXELFORMAT_YVYU()),
    NV12(SDL_PIXELFORMAT_NV12()),
    NV21(SDL_PIXELFORMAT_NV21()),
    P010(SDL_PIXELFORMAT_P010()),
    EXTERNAL_OES(SDL_PIXELFORMAT_EXTERNAL_OES()),
    MJPG(SDL_PIXELFORMAT_MJPG()),
    RGBA32(SDL_PIXELFORMAT_RGBA32()),
    ARGB32(SDL_PIXELFORMAT_ARGB32()),
    BGRA32(SDL_PIXELFORMAT_BGRA32()),
    ABGR32(SDL_PIXELFORMAT_ABGR32()),
    RGBX32(SDL_PIXELFORMAT_RGBX32()),
    XRGB32(SDL_PIXELFORMAT_XRGB32()),
    BGRX32(SDL_PIXELFORMAT_BGRX32()),
    XBGR32(SDL_PIXELFORMAT_XBGR32()),

    ;

    public static PixelFormat fromCode(int code) {
        return Internal.enumFromCode(PixelFormat.class, code, UNKNOWN);
    }

    @Contract("!null -> !null")
    public TextureFormat toTextureFormat(TextureFormat fallback) {
        return TextureFormat.fromPixelFormat(this, fallback);
    }

    @Contract("_, !null -> !null")
    public static PixelFormat fromTextureFormat(TextureFormat textureFormat, @Nullable PixelFormat fallback) {
        return textureFormat.toPixelFormat(fallback);
    }

    private final int code;
    public int code() {
        return this.code;
    }

}
