plugins {
    id 'java'
}

group = 'io.github.plixo2'
version = '0.0.1'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':')

    //annotations
    compileOnly 'org.jetbrains:annotations:23.0.0'

    //lombok
    compileOnly 'org.projectlombok:lombok:1.18.42'
    annotationProcessor 'org.projectlombok:lombok:1.18.42'
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}

tasks.withType(JavaExec).configureEach {
    jvmArgs += "--enable-native-access=ALL-UNNAMED"
}
tasks.withType(Test).configureEach {
    jvmArgs += "--enable-native-access=ALL-UNNAMED"
}