name: Gradle CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 25
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: test with Gradle
        run: ./gradlew clean test --no-build-cache --stacktrace --info